// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {IssuerRegistry} from "../src/IssuerRegistry.sol";
import {VerifiableRecordController} from "../src/VerifiableRecordController.sol";
import {IVerifiableRecordController} from "../src/interfaces/IVerifiableRecordController.sol";

/// @notice Second-implementation check of the signed test vectors published in
///         ENSIP.md §5 and ENSIP-PRIVACY.md §5 (generated by sdk/gen_vectors.mjs
///         with viem). Every hash is recomputed here with raw abi.encode/keccak256
///         and the signature is verified with the ecrecover precompile — no shared
///         code with the generator.
contract TestVectorsTest is Test {
    // Signer: private key 0x...01
    address constant SIGNER = 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf;
    address constant CONTROLLER_ADDR = 0x4242424242424242424242424242424242424242;

    // ── Base RecordRequest vector ─────────────────────────────────────────
    bytes32 constant NODE = 0x787192fc5378cc32aa956ddfdedbf26b24e8d78e40109add0eea2c1a012c3dec;
    bytes32 constant RECORD_DATA_HASH = 0x6e23a506c6a22dc4b781f8b5491e2d26c1d0b32c6ea3edea12ed4c7574afd7ba;
    bytes32 constant BASE_DOMAIN_SEPARATOR = 0xf1bc005db40997cc4699bea62574da4aad06ebad831ee91672e1322a61c37c1a;
    bytes32 constant BASE_STRUCT_HASH = 0x849e81a3dd142e923266842fb5b5cb72db95fbcfe6ba909e4fb131545217368f;
    bytes32 constant BASE_DIGEST = 0x03be0267ae30178d9d936a7e0078bccc8ff4faefe57bac5e29070a4366e3eeb7;
    bytes32 constant CONTENT_KEY = 0x8259d5114ee13141f7669af46c0a30346f3aa8de5ee11145992d38e12c5906e1;
    bytes constant BASE_SIG =
        hex"56551c5a25e0f94174be5ca05585771139fc618bb23f8854a0a56f8d456eb62d6fa3605042208a215eefa165a0e13e46900f3f7140b8e8d4b3dc0f42832caa8b1b";

    // ── Disclosure vector ─────────────────────────────────────────────────
    bytes32 constant PRIV_RECORD_DATA_HASH = 0x08440f9313d3dc4f6c1601f93b58a1b8fb7f93b6473f99fcc680921f1d52e98b;
    bytes32 constant PRIV_DOMAIN_SEPARATOR = 0xaa950cf535f79bee163e4b8cb2325176f654fbfa4375f01f07d56c528c74caa3;
    bytes32 constant PRIV_STRUCT_HASH = 0x72e3a36b640c799a3bfc4ff13967d5bce78d2851a621546ce36bcde50620a15f;
    bytes32 constant PRIV_DIGEST = 0x3807e11ae11125a3a896c047e5f11a78fc6d1b9affd5dc858a834c792e759049;
    bytes32 constant DISCLOSURE_NONCE = 0x3333333333333333333333333333333333333333333333333333333333333333;
    bytes constant PRIV_SIG = hex"fb64548e89c8b164f16121acacc1d23c54e637456abef4524d02ffe030b96e5366641f8f5f607162d78c9a12cf5992825c205182ce245df35c4b91e4246299b6"
        hex"1b";

    function _splitSig(bytes memory sig) internal pure returns (bytes32 r, bytes32 s, uint8 v) {
        require(sig.length == 65, "bad sig length");
        assembly {
            r := mload(add(sig, 0x20))
            s := mload(add(sig, 0x40))
            v := byte(0, mload(add(sig, 0x60)))
        }
    }

    function test_vector_base_recordDataHash_and_node() public pure {
        assertEq(keccak256(bytes("credential-payload")), RECORD_DATA_HASH);
        // namehash("alice.eth") = keccak256(namehash("eth") || labelhash("alice"))
        bytes32 ethNode = keccak256(abi.encodePacked(bytes32(0), keccak256(bytes("eth"))));
        assertEq(keccak256(abi.encodePacked(ethNode, keccak256(bytes("alice")))), NODE);
    }

    function test_vector_base_domainSeparator() public pure {
        bytes32 ds = keccak256(
            abi.encode(
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256("ENS Verifiable Records"),
                keccak256("1"),
                uint256(1),
                CONTROLLER_ADDR
            )
        );
        assertEq(ds, BASE_DOMAIN_SEPARATOR);
    }

    function test_vector_base_structHash_digest_signature() public pure {
        bytes32 typehash = keccak256(
            "RecordRequest(bytes32 node,string ensName,address resolver,string recordType,bytes32 recordDataHash,address issuer,uint64 expires,uint256 nonce)"
        );
        bytes32 structHash = keccak256(
            abi.encode(
                typehash,
                NODE,
                keccak256(bytes("alice.eth")),
                address(0x1111111111111111111111111111111111111111),
                keccak256(bytes("identity")),
                RECORD_DATA_HASH,
                address(0x2222222222222222222222222222222222222222),
                uint64(1735689600),
                uint256(0)
            )
        );
        assertEq(structHash, BASE_STRUCT_HASH);

        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", BASE_DOMAIN_SEPARATOR, structHash));
        assertEq(digest, BASE_DIGEST);

        (bytes32 r, bytes32 s, uint8 v) = _splitSig(BASE_SIG);
        assertEq(ecrecover(digest, v, r, s), SIGNER);
    }

    function test_vector_base_contentKey_via_reference_controller() public {
        IssuerRegistry registry = new IssuerRegistry();
        VerifiableRecordController controller = new VerifiableRecordController(address(registry));

        IVerifiableRecordController.RecordRequest memory request = IVerifiableRecordController.RecordRequest({
            node: NODE,
            ensName: "alice.eth",
            resolver: 0x1111111111111111111111111111111111111111,
            recordType: "identity",
            recordDataHash: RECORD_DATA_HASH,
            issuer: 0x2222222222222222222222222222222222222222,
            expires: 1735689600,
            nonce: 0
        });
        assertEq(controller.computeContentKey(request, BASE_SIG), CONTENT_KEY);
    }

    function test_vector_privacy_saltedHash() public pure {
        bytes32 salt = 0x1111111111111111111111111111111111111111111111111111111111111111;
        assertEq(keccak256(abi.encodePacked(salt, bytes("alice@example.com"))), PRIV_RECORD_DATA_HASH);
    }

    function test_vector_privacy_disclosure() public pure {
        bytes32 ds = keccak256(
            abi.encode(
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256("ENS Selective Disclosure"),
                keccak256("1"),
                uint256(1),
                CONTROLLER_ADDR
            )
        );
        assertEq(ds, PRIV_DOMAIN_SEPARATOR);

        bytes32 typehash = keccak256(
            "Disclosure(bytes32 node,address issuer,string recordType,bytes32 nonce,address vendor,string vendorIdentity,uint64 expires)"
        );
        bytes32 structHash = keccak256(
            abi.encode(
                typehash,
                NODE,
                address(0x2222222222222222222222222222222222222222),
                keccak256(bytes("email")),
                DISCLOSURE_NONCE,
                address(0),
                keccak256(bytes("https://vendor.example.com")),
                uint64(0)
            )
        );
        assertEq(structHash, PRIV_STRUCT_HASH);

        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", ds, structHash));
        assertEq(digest, PRIV_DIGEST);

        (bytes32 r, bytes32 s, uint8 v) = _splitSig(PRIV_SIG);
        assertEq(ecrecover(digest, v, r, s), SIGNER);
    }
}
